(function(global){
  'use strict';
  var crcTable=null;
  function crc32(bytes){if(!crcTable){crcTable=[];for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);crcTable[n]=c>>>0;}}var crc=0xffffffff;for(var i=0;i<bytes.length;i++)crc=crcTable[(crc^bytes[i])&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
  function join(parts){var len=parts.reduce(function(s,p){return s+p.length},0),out=new Uint8Array(len),pos=0;parts.forEach(function(p){out.set(p,pos);pos+=p.length;});return out;}
  function zip(files){var enc=new TextEncoder(),locals=[],centrals=[],offset=0,now=new Date(),dt=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1),dd=((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();function u16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function u32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}Object.keys(files).forEach(function(path){var name=enc.encode(path),data=enc.encode(files[path]),crc=crc32(data),local=join([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(dt),u16(dd),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(dt),u16(dd),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;});var central=join(centrals),end=join([u32(0x06054b50),u16(0),u16(0),u16(centrals.length),u16(centrals.length),u32(central.length),u32(offset),u16(0)]);return new Blob([join(locals.concat([central,end]))],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function tr(v){return global.cncTranslate?global.cncTranslate(v):v;}
  function col(n){var s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
  function cell(r,c,v,style){return '<c r="'+col(c)+r+'" t="inlineStr" s="'+(style||0)+'"><is><t xml:space="preserve">'+esc(v)+'</t></is></c>';}
  function sheetXml(title,headers,rows,widths){var out=[],count=Math.max(headers.length,1),last=Math.max(rows.length+4,4);out.push('<row r="1" ht="34" customHeight="1">'+cell(1,1,title,1)+'</row>');out.push('<row r="2" ht="25" customHeight="1">'+cell(2,1,tr('Vygenerované')+': '+new Date().toLocaleString(),2)+'</row>');out.push('<row r="4" ht="32" customHeight="1">'+headers.map(function(h,i){return cell(4,i+1,tr(h),3);}).join('')+'</row>');rows.forEach(function(row,i){var rn=i+5;out.push('<row r="'+rn+'" ht="54" customHeight="1">'+row.map(function(v,j){return cell(rn,j+1,v,i%2?5:4);}).join('')+'</row>');});var cols=(widths||headers.map(function(){return 24;})).map(function(w,i){return '<col min="'+(i+1)+'" max="'+(i+1)+'" width="'+w+'" customWidth="1"/>';}).join('');return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="4" topLeftCell="A5" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+cols+'</cols><sheetData>'+out.join('')+'</sheetData><autoFilter ref="A4:'+col(count)+last+'"/><mergeCells count="2"><mergeCell ref="A1:'+col(count)+'1"/><mergeCell ref="A2:'+col(count)+'2"/></mergeCells><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>';}
  function val(v,fallback){return v==null||v===''?(fallback||'—'):v;}
  function build(data){data=data||{};var setup=data.setup||{},setups=Array.isArray(data.setups)?data.setups:[],ops=Array.isArray(data.operations)?data.operations:[],tools=Array.isArray(data.tools)?data.tools:[],params=Array.isArray(data.parameters)?data.parameters:[];
    var summary=[[tr('Výkres'),val(data.file)],[tr('Typ obrábania'),val(data.operation)],[tr('Materiál'),val(data.material)],[tr('Stav a tvrdosť materiálu'),val(data.materialCondition)],[tr('Polotovar'),val(data.stock)],[tr('Stroj'),val(data.machineSummary||data.machine)],[tr('CNC riadenie'),val(data.control)],[tr('Čítanie výkresu'),val(data.drawing_read)],[tr('Upnutie'),val(setup.clamping)],[tr('Nulový bod'),val(setup.datum)],[tr('Opory'),val(setup.supports)],[tr('Riziká'),val(setup.risks)]];
    var setupRows=setups.map(function(s){return[val(s.setup_no),val(s.name),val(s.clamping),val(s.jaw_type),val(s.stickout),val(s.datum),val(s.datum_shift),val(s.machining_length),val(s.reclamping_reference),val(s.risks)];});
    var opRows=ops.map(function(o){return[val(o.order),val(o.setup_no),val(o.name),val(o.description),val(o.machining_scope),val(o.tool_id),val(o.target_dimensions),val(o.stock_allowance),val(o.tool_reuse)];});
    var norm=function(x){return String(x||'').trim().toLowerCase();};
    var toolRows=tools.map(function(t){var p=params.find(function(x){return norm(x.operation)===norm(t.operation);})||params.find(function(x){return norm(x.operation).includes(norm(t.operation))||norm(t.operation).includes(norm(x.operation));})||{};return[val(t.tool_id),val(t.operation),val(t.tool_type||t.tool),val(t.quantity,1),val(t.manufacturer),val(t.holder_or_body||t.holder),val(t.holder_or_body_code),val(t.insert_or_tool||t.insert),val(t.insert_or_tool_code),val(t.grade),val(t.geometry),val(t.compatibility),val(p.vc||t.vc),val(p.rpm||t.rpm),val(p.feed||t.feed),val(p.fz),val(p.ap),val(p.ae),val(p.coolant),val(t.reason),val(t.verification_status)];});
    var quality=[];[['Kritické rozmery',data.critical_dimensions],['Prvky výkresu',(data.drawing_features||[]).map(function(f){return [f.feature_scope,f.feature,f.value,f.location,f.source].filter(Boolean).join(' | ');})],['Preverené katalógy',data.tool_sources],['Upozornenia',data.warnings],['Poznámky',data.notes]].forEach(function(g){(Array.isArray(g[1])?g[1]:[]).forEach(function(x,i){quality.push([tr(g[0]),i+1,typeof x==='string'?x:JSON.stringify(x)]);});});
    var sheets=[
      sheetXml(tr('CNC AI TECHNOLÓG – TECHNOLOGICKÁ ANALÝZA'),['Položka','Hodnota'],summary,[30,100]),
      sheetXml(tr('UPNUTIA'),['Č.','Názov','Upnutie','Čeľuste','Vyloženie','Nulový bod','Posun / prídavok','Obrábaná dĺžka','Referencia pre preupnutie','Riziká'],setupRows,[8,24,34,22,18,24,22,22,30,40]),
      sheetXml(tr('TECHNOLOGICKÝ POSTUP'),['Poradie','Upnutie','Operácia','Opis','Oblasť','Nástroj','Cieľové rozmery','Prídavok','Opakované použitie'],opRows,[10,10,28,55,28,16,30,18,28]),
      sheetXml(tr('NÁSTROJE A REZNÉ PARAMETRE'),['ID','Operácia','Typ nástroja','Počet','Výrobca','Držiak / teleso','Kód držiaka / telesa','Plátok / vrták / fréza','Presný kód nástroja','Trieda','Geometria','Kompatibilita','vc','Otáčky','Posuv','fz','ap','ae','Chladenie','Dôvod výberu','Overenie katalógu'],toolRows,[8,24,26,9,20,28,28,28,30,18,22,30,12,14,16,12,12,12,20,45,22]),
      sheetXml(tr('KONTROLA A POZNÁMKY'),['Sekcia','Č.','Obsah'],quality,[28,8,110])
    ];
    var names=['Suhrn','Upnutia','Technologicky postup','Nastroje a parametre','Kontrola'];
    var styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="18"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B5F91"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FF123D5A"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF3F7FA"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE7F2F8"/></patternFill></fill></fills><borders count="2"><border/><border><bottom style="thin"><color rgb="FFC5D3DC"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="5" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="4" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
    var wbSheets=names.map(function(n,i){return '<sheet name="'+esc(n)+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>';}).join(''),rels=names.map(function(n,i){return '<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>';}).join('')+'<Relationship Id="rId'+(names.length+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>';
    var overrides=names.map(function(n,i){return '<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';}).join(''),files={'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+overrides+'</Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+wbSheets+'</sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+rels+'</Relationships>','xl/styles.xml':styles};sheets.forEach(function(s,i){files['xl/worksheets/sheet'+(i+1)+'.xml']=s;});return zip(files);
  }
  global.cncBuildAnalysisXlsx=build;
})(typeof window!=='undefined'?window:globalThis);
