(function(global){
  'use strict';
  var crcTable=null;
  function crc32(bytes){
    if(!crcTable){crcTable=[];for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);crcTable[n]=c>>>0;}}
    var crc=0xffffffff;for(var i=0;i<bytes.length;i++)crc=crcTable[(crc^bytes[i])&255]^(crc>>>8);return (crc^0xffffffff)>>>0;
  }
  function join(parts){var len=parts.reduce(function(s,p){return s+p.length},0),out=new Uint8Array(len),pos=0;parts.forEach(function(p){out.set(p,pos);pos+=p.length});return out;}
  function zip(files){
    var enc=new TextEncoder(),locals=[],centrals=[],offset=0,now=new Date(),dosTime=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1),dosDate=((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
    function u16(v){return new Uint8Array([v&255,(v>>>8)&255]);}function u32(v){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);}
    Object.keys(files).forEach(function(path){var name=enc.encode(path),data=enc.encode(files[path]),crc=crc32(data),local=join([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(dosTime),u16(dosDate),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(dosTime),u16(dosDate),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;});
    var central=join(centrals),end=join([u32(0x06054b50),u16(0),u16(0),u16(centrals.length),u16(centrals.length),u32(central.length),u32(offset),u16(0)]);return new Blob([join(locals.concat([central,end]))],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  }
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function cell(ref,value,style){return '<c r="'+ref+'" t="inlineStr" s="'+style+'"><is><t xml:space="preserve">'+esc(value)+'</t></is></c>';}
  function build(data,rows){
    var sheetRows=[];
    sheetRows.push('<row r="1" ht="32" customHeight="1">'+cell('A1','CNC AI TECHNOLÓG – POROVNANIE NÁHRAD NÁSTROJA',1)+'</row>');
    sheetRows.push('<row r="2" ht="24" customHeight="1">'+cell('A2','Pôvodný nástroj',2)+cell('B2',data.original_designation||'NEPOTVRDENÉ',3)+cell('G2','Materiál',2)+cell('H2',data.input_material||'NEZADANÝ',3)+'</row>');
    sheetRows.push('<row r="3" ht="24" customHeight="1">'+cell('A3','Operácia',2)+cell('B3',data.input_operation||'NEZADANÁ',3)+cell('G3','Štýl obrábania',2)+cell('H3',data.input_machining_style||'NEZADANÝ',3)+'</row>');
    sheetRows.push('<row r="4" ht="30" customHeight="1">'+cell('A4','Vygenerované: '+new Date().toLocaleString('sk-SK')+'. Hodnoty sú štartovacie; pred použitím ich over podľa stroja, upnutia a podmienok rezu.',4)+'</row>');
    var headers=['Položka','Dodávateľ / výrobca','Presné označenie','Trieda','Teleso alebo držiak','Opis / použitie','Štartovacie parametre','Chladenie / stratégia','Zhoda','Porovnanie','Overenie'];
    sheetRows.push('<row r="5" ht="34" customHeight="1">'+headers.map(function(v,i){return cell(String.fromCharCode(65+i)+'5',v,5)}).join('')+'</row>');
    rows.forEach(function(r,i){var rn=i+6,style=i===0?6:(i===1?7:8),params='vc: '+r.vc+' m/min\nn: '+r.rpm+' ot/min\nf: '+r.feed+'\nap: '+r.ap+' mm\nae: '+r.ae+' mm',supplier=r.supplier+'\n'+r.manufacturer,cooling='Chladenie: '+r.coolant+'\nStratégia: '+r.strategy,values=[r.kind,supplier,r.code,r.grade,r.companion,r.type,params,cooling,r.match,r.comparison,r.verification];sheetRows.push('<row r="'+rn+'" ht="88" customHeight="1">'+values.map(function(v,j){return cell(String.fromCharCode(65+j)+rn,v,style)}).join('')+'</row>');});
    var last=rows.length+5,sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="18" customWidth="1"/><col min="2" max="2" width="24" customWidth="1"/><col min="3" max="3" width="30" customWidth="1"/><col min="4" max="4" width="18" customWidth="1"/><col min="5" max="6" width="30" customWidth="1"/><col min="7" max="8" width="25" customWidth="1"/><col min="9" max="9" width="20" customWidth="1"/><col min="10" max="10" width="34" customWidth="1"/><col min="11" max="11" width="20" customWidth="1"/></cols><sheetData>'+sheetRows.join('')+'</sheetData><autoFilter ref="A5:K'+last+'"/><mergeCells count="6"><mergeCell ref="A1:K1"/><mergeCell ref="B2:F2"/><mergeCell ref="H2:K2"/><mergeCell ref="B3:F3"/><mergeCell ref="H3:K3"/><mergeCell ref="A4:K4"/></mergeCells><pageMargins left="0.25" right="0.25" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>';
    var styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="18"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="7"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0D5F91"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF4FB"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEEF2F5"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE8F6EC"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFFFFF"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFB8C7D1"/></left><right style="thin"><color rgb="FFB8C7D1"/></right><top style="thin"><color rgb="FFB8C7D1"/></top><bottom style="thin"><color rgb="FFB8C7D1"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="6" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="4" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="5" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="6" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
    return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Nahrady nastrojov" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>','xl/styles.xml':styles,'xl/worksheets/sheet1.xml':sheet});
  }
  global.cncBuildProfessionalXlsx=build;
})(typeof window!=='undefined'?window:globalThis);
